# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml
---
:verbose: false
:concurrency:  <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
:pidfile: tmp/pids/sidekiq.pid
:queues:
  - critical
  - default
  - low